version: '3.9'

services:
  backend:
    build: ./healthcare_API
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./healthcare_API:/app
    environment:
      - DEBUG=1
      - POSTGRES_DB=healthcare_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy  # データベースのヘルスチェックが完了してから起動
    command: >
      sh -c "
      python manage.py migrate &&
      python create_superuser.py &&
      python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    container_name: healthcare_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: healthcare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./healthcare_front
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./healthcare_front:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  # ホットリロード対応

volumes:
  postgres_data:  # ここでボリュームを定義
